version: '2.2'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: raccoon
            POSTGRES_PASSWORD: test
            POSTGRES_DB: raccoon-db
        volumes:
            - ./pg_data:/var/lib/postgresql/data

    app:
        build: .
        working_dir: /usr/src/app
        ports:
            - 3000:3000
        command: npm run dev
