version: '2.2'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: raccoon
            POSTGRES_PASSWORD: test
            POSTGRES_DB: raccoon-db
        volumes:
            - ./pg_data:/var/lib/postgresql/data
